### ISSUE TITLE
TRUE 0 PRED [0.]

### ISSUE THREAD

**Issue by pavelxx1** [FrancescoMandru/siamese-network#1]
always had result after testing =(

**Comment by FrancescoMandru** [comment]
Hi @pavelxx1 , what do you mean? Please try to be clearer.

**Comment by pavelxx1** [comment]
after successfully training ,when I do inference ,
result always false (

**Comment by FrancescoMandru** [comment]
Sorry, but without your dataset and your steps I can't help you. During training you have validation dataset that tells you if the model is learning correctly the task.
